---
- name: Verify Syncthing is running
  uri:
    url: https://localhost:8384/rest/config
    method: GET
    return_content: yes
    headers:
      X-API-Key: "{{ syncthing_api_key }}"
    validate_certs: no
    status_code: 200
    body_format: json
  register: syncthing_verification_result
  until: syncthing_verification_result.status == 200
  retries: 5
  delay: 10

- name: Create volume storage directory
  file:
    path: /storage/knocknoc-cloud/{{ syncthing_volume_name }}/
    state: directory
    owner: syncthing
    group: syncthing
    mode: '0755'

- name: Create user for Syncthing GUI
  ansible.builtin.command:
    cmd: "sudo -u syncthing syncthing cli config gui user set {{ syncthing_gui_user }}"
  become: yes
  ignore_errors: yes

- name: Set password for Syncthing GUI
  ansible.builtin.command:
    cmd: "sudo -u syncthing syncthing cli config gui password set {{ syncthing_gui_password }}"
  become: yes
  ignore_errors: yes

- name: Add device in Syncthing configuration
  ansible.builtin.command:
    cmd: "sudo -u syncthing syncthing cli config devices add --device-id {{ syncthing_replica_guid }} --name {{ syncthing_replica_host }}"
  become: yes

- name: Auto accept from Syncthing Partner Host
  ansible.builtin.command:
    cmd: "sudo -u syncthing syncthing cli config devices {{ syncthing_replica_guid }} auto-accept-folders set true"
  become: yes

- name: Grab list of existing folders to use for when clause
  ansible.builtin.command:
    cmd: "sudo -u syncthing syncthing cli config folders list"
  register: syncthing_folder_result
  become: yes

- name: Add docker-volumes folder in Syncthing configuration for Primary
  ansible.builtin.command:
    cmd: "sudo -u syncthing syncthing cli config folders add --id {{ syncthing_volume_name }} --label {{ syncthing_volume_name }} --path /storage/knocknoc-cloud/{{ syncthing_volume_name }}/ --type sendonly --rescan-intervals 300"
  become: yes
  when: 
    - syncthing_volume_name not in syncthing_folder_result.stdout_lines
    - inventory_hostname.endswith('ct1')

- name: Add docker-volumes folder in Syncthing configuration for Secondary
  ansible.builtin.command:
    cmd: "sudo -u syncthing syncthing cli config folders add --id {{ syncthing_volume_name }} --label {{ syncthing_volume_name }} --path /storage/knocknoc-cloud/{{ syncthing_volume_name }}/ --type receiveonly --rescan-intervals 300" 
  become: yes
  when: 
    - syncthing_volume_name not in syncthing_folder_result.stdout_lines 
    - inventory_hostname.endswith('ct2')

- name: Share Docker Folder
  ansible.builtin.command:
    cmd: "sudo -u syncthing syncthing cli config folders {{ syncthing_volume_name }} devices add --device-id {{ syncthing_replica_guid }}"
  become: yes