---
- name: Wait for Syncthing config file to exist
  ansible.builtin.wait_for:
    path: "{{ syncthing_config_file }}"
    state: present
    timeout: 60
  become: true

- name: Extract API Key from Syncthing config
  community.general.xml:
    path: "{{ syncthing_config_file }}"
    xpath: /configuration/gui/apikey
    content: text
  register: _syncthing_api_key_result
  become: true

- name: Set API Key fact
  ansible.builtin.set_fact:
    syncthing_api_key: "{{ _syncthing_api_key_result.matches[0].apikey }}"

- name: Extract Device ID from local Syncthing config
  community.general.xml:
    path: "{{ syncthing_config_file }}"
    xpath: /configuration/device
    content: attribute
  register: _syncthing_device_id_result
  become: true

- name: Set Device ID fact
  ansible.builtin.set_fact:
    syncthing_device_id: "{{ _syncthing_device_id_result.matches[0].device.id }}"
