---
- name: Verify Syncthing User and Password vars are set
  ansible.builtin.include_tasks: vars.yml

- name: Install Syncthing and Setup Service
  ansible.builtin.include_tasks: install.yml

- name: Grab API and Device ID vars from local config
  ansible.builtin.include_tasks: extract_from_local_config.yml

- name: Configure Syncthing application
  ansible.builtin.include_tasks: configure_app.yml

- name: Configure Syncthing devices
  ansible.builtin.include_tasks: configure_devices.yml

- name: Configure Syncthing sync folders
  ansible.builtin.include_tasks: configure_folder.yml