---
- name: Install syncthing and dependencies 
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - curl
    - syncthing
    - python3-lxml

- name: Ensure system user 'syncthing' exists
  ansible.builtin.user:
    name: syncthing
    uid: 9001
    shell: /sbin/nologin
    system: yes
    create_home: yes

- name: Ensure syncthing systemd service exists
  ansible.builtin.template:
    src: templates/syncthing.service.j2
    dest: /etc/systemd/system/syncthing.service

- name: Ensure Syncthing service is enabled and started
  ansible.builtin.systemd:
    name: syncthing.service
    enabled: yes
    state: started
    daemon_reload: yes
